[project]
name = "toshokan-goals"
version = "0.1.0"
description = "Toshokan goals feature module."
authors = [
    {name = "ishish.io",email = "ts@ishish.io"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "fastapi (>=0.128.0,<0.129.0)",
    "pydantic (>=2.0.0,<3.0.0)"
]
packages = [{include = "toshokan_goals"}]

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"

[tool.poetry]
packages = [{include = "toshokan_goals"}]

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.2"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
