[project]
name = "toshokan-conversation"
version = "0.1.0"
description = "Toshokan conversation feature module."
authors = [
    {name = "ishish.io",email = "ts@ishish.io"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "fastapi (>=0.128.0,<0.129.0)",
    "pydantic (>=2.0.0,<3.0.0)"
]
packages = [{include = "toshokan_conversation"}]

[tool.poetry]
packages = [{include = "toshokan_conversation"}]
include = ["toshokan_conversation/adapters/*.json"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
